# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fe2a734669d9ae2df78591f476383762eddc6736bb0ef772b5f7319782211327997745c1120fb0cc43f584fcf7dafac9a59600fb7aa1dc2c744f1092794467b

test:
  secret_key_base: 432ad4fdae9ed69d23f5f97f189c8a6c7f2647be5a7b78aabf7ed80fd63bcb9ca95356bc6593a8b8bf2f188101e05117da8beadfd7d3d9364a255ff14a862cef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
